### ISSUE TITLE
Message text on Delete Ledger dialog is confusing

### ISSUE THREAD

**Issue by Tr3yb0** [fluree/fluree-admin-ui#18]
Currently the prompt for what to type to delete a ledger is confusing.

"Please, enter "confirm" to DELETE ledger."

Can this be changed to either say 
- "Please type CONFIRM to delete this ledger" with delete in lower-case
or
- "Please, type DELETE to DELETE this ledger." with DELETE being the string which toggles the validation on the submit button for the form?

I have also seen this kind of thing done where the user must type the name of the resource into the dialog input, with the resource name surface in the prompt for easy copy-pasting, which i quite like.

**Comment by ldw1007** [comment]
Hi Trey - created a ticket for you; we are tracking this issue with FC-1132.
