### ISSUE TITLE
Schema explorer swallowing errors

### ISSUE THREAD

**Issue by Tr3yb0** [fluree/fluree-admin-ui#19]
If an error is thrown when launching the schema explorer, the error is not handled properly by the UI it hangs. 
Ex. I transacted a predicate with the name display-name, which is not a valid predicate name. The transaction was successful (which might be a separate bug). When I attempted to launch the Schema Explorer, it hung on the loading screen and only threw the error to the browser console.

**Comment by ldw1007** [comment]
Hi Trey, we are using a 3rd party utility for the schema explorer.  I created a research ticket; we are tracking with FC-1133
