### ISSUE TITLE
Change Config not working

### ISSUE THREAD

**Issue by trancephorm** [fluree/fluree-admin-ui#20]
Change Config (top right corner), then Change Config option from drop down menus opens a window where you can't change the server you're connecting to. Esc is not working, page must be refreshed to exit this bug. 

Chrome Linux 64bit version 90.0.4430.212

**Comment by ldw1007** [comment]
Hi @trancephorm 

The Change Config model has been reworked recently.  Which version of Fluree are you using - the latest (e.g., 1.0.0-something) or stable (0.16-something)?

**Comment by trancephorm** [comment]
Fluree Ledger 1.0.0-beta11
Fluree Admin UI 1.0.0-rc5
